#!/usr/bin/env python

import getopt
import sys, os

from urllib.request import urlopen
from bs4 import BeautifulSoup

Targets = ["linux", "mac", "windows", "android", "audio"]

# import configparser

# config = configparser.ConfigParser()
# config.read('example.cfg')

class Download():
    def __init__(self, bt, web, md5):
        self.bt  = bt
        self.web = web
        self.md5 = md5

class Game():
    def __init__(self, title, sub, url):
        self.title = title
        self.subtitle = sub
        self.url = url
        self.files = {}

class HumbleBundle():
    def __init__(self, key):
        url = "https://www.humblebundle.com/downloads?key={0}".format(key)
        print("Opening:", url)
        html = urlopen(url)

        self.games = []

        soup = BeautifulSoup(html.read())
        for row in soup.find_all("div", { "class" : "row" }):
            game = self.parse_game(row)
            # self.games[name] = game
            self.games.append(game)

    def parse_game(self, row):
        a     = row.find("div", { "class" : "title" }).contents[0]
        title = a.contents[0]
        url   = a['href']
        sub   = row.find("div", { "class" : "subtitle" }).contents[0].contents[0]
        game  = Game(title, sub, url)

        for target in Targets:
            files = []
            downloads = row.find("div", { "class" : target })
            for dl in downloads.find_all('a'):
                bt, web = None, None
                if 'data-bt' in dl.attrs:
                    bt = dl['data-bt']
                if 'data-web' in dl.attrs:
                    web = dl['data-web']
                if bt or web:
                    files.append(Download(bt, web, None))

                # if 'dlmd5' in dl['class']:
                #     print("MD5:       ", dl['href'])
            game.files[target] = files

        return game

def usage():
    pass

def main():
    try:
        opts, args = getopt.getopt(sys.argv[1:], "b:t:f:v", ["bundle=", "target=", "file=", "key=", "verbose", "as-root"])
    except getopt.GetoptError as err:
        print(err, file=sys.stderr)
        usage()
        sys.exit(2)

    root = False
    verbose = False
    targets = Targets

    for o, a in opts:
        if o in ("-b", "--bundle"):
            print("Loading bundle", a)
        elif o in ("-t", "--target"):
            # TODO: verify targets
            targets = a.split(",")
        elif o in ("-k", "--key"):
            key = a
        elif o in ("-v", "--verbose"):
            verbose = True
        elif o == "--as-root":
            root = True
        else:
            assert False, "unhandled option"

    if not root and os.geteuid() == 0:
        print("Running as root requires --as-root", file=sys.stderr)
        sys.exit(1)

    bundle = HumbleBundle(key)
    # for link in parser.links:
    #     print(link)

    for g in bundle.games:
        print(g.title)
        print(g.url)
        print()

        for t in targets:
            for f in g.files[t]:
                print(f.bt)
        print()

if __name__ == "__main__":
    main()
